### ISSUE TITLE
Indenting support for Gherkin

### ISSUE THREAD

**Issue by yoshikin** [fulstech/markin#14]
Would it be possible to implement indenting support for Gherkin syntax?

See this example of a Gherkin Feature and Scenario:

![image](https://cloud.githubusercontent.com/assets/10310897/20134165/bc8afd58-a66a-11e6-9420-f2210424535e.png)

The Scenario title is indented and the Given/When/Then are indented even more so that the hierarchy is easy to see visually.

Currently, if add spaces of tabs at the beginning of a line, Markin just ignores them.

You could either implement automatic indenting for Gherkin keywords or at least allow the user to add his own tabs and spaces... but I imagine this would conflict with the Markdown parsing?

**Comment by fulstech** [comment]
@yoshikin,

Because Markdown syntax does not allow multiple spaces and it is also cumbersome to do manual indentation, so automatic indentation will be the best choice here. This feature will be delivered in two weeks.

Are you satisfied with our proposal? If you have any requests, do not hesitate to let us know, we will be very happy to support you.

**Comment by yoshikin** [comment]
Thanks for your response. Yes, automatic indenting would be great.

**Comment by fulstech** [comment]
Hi @yoshikin,

Please check out the latest version. We added a new option in the field configuration page:

![gherkin-2](https://cloud.githubusercontent.com/assets/17452401/21525616/0eca1542-cd51-11e6-8ef9-fb611e3a01fc.jpg)

To enable Gherkin syntax highlighting and indenting.

To access the configuration page please follow the link at the bottom of the field's content.
